dist: xenial

language: python

python:
    - "3.7"

install:
    - pip install -r requirements.txt
    - rm -rf out/* || exit 0

script:
    - make build 

deploy:
    local_dir: out
    repo: boot-error/boot-error.github.io
    target_branch: master
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
